version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:/app/database.sqlite
    volumes:
      - ./database.sqlite:/app/database.sqlite