version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:/app/database.sqlite
      - ELASTIC_APM_SECRET_TOKEN=your_apm_secret_token
      - ELASTIC_APM_SERVER_URL=https://elastic.netprovider.cl:8200
      - SERVICE_NAME=app_apm_express
    volumes:
      - ./database.sqlite:/app/database.sqlite